---
- name: Stat php conf dir
  stat: path={{ php_conf_path }}
  register: php_conf_dir
  
- name: Stat php extension conf dir
  stat: path={{ php_extension_conf_path }} follow=true
  register: php_extension_conf_dir

- name: Stat mods-available
  stat: path={{ php_mods_available_path }}
  register: php_mods_available_dir

- name: Check if mods-available exists
  set_fact:
    mods_available_exists: "{{ php_mods_available_dir.stat.isdir is defined and php_mods_available_dir.stat.isdir }}"

- name: Ensure configuration directories exist.
  assert:
    that:
      - php_conf_exists: php_conf_dir.stat.isdir is defined and php_conf_dir.stat.isdir
      - php_extension_conf_exists: php_extension_conf_dir.stat.isdir is defined and php_extension_conf_dir.stat.isdir

- name: Place PHP configuration file in place.
  template:
    src: php.ini.j2
    dest: "{{ php_conf_path }}/php.ini"
    owner: root
    group: root
    mode: 0644
  notify: restart webserver
  when: php_use_managed_ini

- name: Place APC configuration file into extension conf dir.
  template:
    src: apc.ini.j2
    dest: "{{ php_extension_conf_path }}/{{ php_apc_conf_filename }}"
    owner: root
    group: root
    mode: 0644
  when: php_enable_apc and not mods_available_exists|bool
  notify: restart webserver

- name: Place APC configuration file into mods_available.
  template:
    src: apc.ini.j2
    dest: "{{ php_mods_available_path }}/{{ php_apc_conf_ma_filename }}"
    owner: root
    group: root
    mode: 0644
  when: php_enable_apc and mods_available_exists|bool
  notify: restart webserver

- name: Ensure php-fpm is started and enabled at boot (if configured).
  service:
    name: "{{ php_fpm_daemon }}"
    state: started
    enabled: yes
  when: php_enable_php_fpm
